"""EventDispatcher — routes live bar data from Bridge POST endpoints
to the 6 trading systems based on their subscribed_streams declarations.

Thread-safe: bars arrive from FastAPI endpoint handlers which may run
on different threads (uvicorn thread pool).
"""

import logging
import threading
from collections import defaultdict
from typing import Any, Dict, List, Optional

from backend.v9.systems.base_system import BaseSystem, Signal

logger = logging.getLogger(__name__)


class EventDispatcher:
    """Central routing layer: stream_name -> list of subscribed systems.

    Usage:
        dispatcher = EventDispatcher(gateway=trading_gateway)
        dispatcher.register_system(day_type_system)
        dispatcher.register_system(chart_5min_system)
        ...
        # On every Bridge POST:
        dispatcher.on_bar_received("cumulative_delta", bar_dict)
    """

    def __init__(self, gateway: Any = None):
        """Initialize the dispatcher.

        Args:
            gateway: TradingGateway instance for forwarding signals from
                     firing systems. If None, signals are logged but not routed.
        """
        self._gateway = gateway
        self._routing_table: Dict[str, List[BaseSystem]] = defaultdict(list)
        self._systems: Dict[int, BaseSystem] = {}
        self._lock = threading.Lock()
        self._stream_health = None

    def set_stream_health(self, service) -> None:
        """Inject StreamHealthService for dispatch tracking."""
        self._stream_health = service

    def register_system(self, system: BaseSystem) -> None:
        """Register a system and add it to the routing table.

        Reads system.subscribed_streams and maps each stream to this system.
        """
        with self._lock:
            if system.system_id in self._systems:
                logger.warning(
                    "[EventDispatcher] system %d (%s) already registered, skipping",
                    system.system_id, system.name,
                )
                return

            self._systems[system.system_id] = system

            for stream in system.subscribed_streams:
                self._routing_table[stream].append(system)
                logger.info(
                    "[EventDispatcher] registered system %d (%s) for stream '%s'",
                    system.system_id, system.name, stream,
                )

    def on_bar_received(self, stream_name: str, bar: dict) -> List[Signal]:
        """Route a bar to all systems subscribed to this stream.

        For each subscribed system:
        - Calls system.analyze(stream_name, bar)
        - If analyze() returns a Signal, forwards to TradingGateway.route_setup()
        - Errors in one system do not prevent other systems from receiving the bar

        Args:
            stream_name: The stream identifier (e.g. "cumulative_delta").
            bar: Raw bar dict from the Bridge POST payload.

        Returns:
            List of Signal objects generated by systems (may be empty).
        """
        with self._lock:
            subscribers = list(self._routing_table.get(stream_name, []))

        if not subscribers:
            return []

        signals: List[Signal] = []

        for system in subscribers:
            logger.info(
                "[EventDispatcher] routing %s to system %d (%s)",
                stream_name, system.system_id, system.name,
            )
            try:
                result = system.analyze(stream_name, bar)
                if self._stream_health is not None:
                    self._stream_health.record_dispatch(stream_name, system.system_id)
                if result is not None and isinstance(result, Signal):
                    logger.info(
                        "[EventDispatcher] signal from system %d (%s): %s %s",
                        system.system_id, system.name,
                        result.direction, result.classification,
                    )
                    signals.append(result)
                    self._forward_signal(result, system.system_id)
            except Exception:
                logger.exception(
                    "[EventDispatcher] error in system %d (%s) processing %s",
                    system.system_id, system.name, stream_name,
                )

        return signals

    def get_routing_table(self) -> Dict[str, List[int]]:
        """Return a summary of the routing table: stream -> list of system IDs."""
        with self._lock:
            return {
                stream: [s.system_id for s in systems]
                for stream, systems in self._routing_table.items()
            }

    def get_registered_systems(self) -> Dict[int, str]:
        """Return registered systems: system_id -> name."""
        with self._lock:
            return {sid: s.name for sid, s in self._systems.items()}

    def _forward_signal(self, signal: Signal, system_id: int) -> None:
        """Forward a signal to the TradingGateway for trade execution."""
        if self._gateway is None:
            return

        setup = {
            "firing_system": signal.system_id,
            "direction": signal.direction,
            "classification": signal.classification,
            "confidence": signal.confidence,
            "stop": signal.stop or 0.0,
            "t1": signal.targets[0] if signal.targets and len(signal.targets) > 0 else 0.0,
            "t2": signal.targets[1] if signal.targets and len(signal.targets) > 1 else 0.0,
            "t3": signal.targets[2] if signal.targets and len(signal.targets) > 2 else 0.0,
            "entry_price": signal.entry_price,
            "metadata": signal.metadata,
        }

        try:
            self._gateway.route_setup(setup, system_id)
        except Exception:
            logger.exception(
                "[EventDispatcher] failed to forward signal from system %d to gateway",
                system_id,
            )
