#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_measurement_index — one place that answers "did we already measure this?"

Michael 2026-09-08: "כבר ביצענו מלא בדיקות — אפשר להתייעל ולעשות אינדקס לכל
הבדיקות ומה נמדד, כדי לא לחפש שעות כל פעם."

589 files sit in docs/reports/. Most are status or handoff notes; a minority
carry a MEASUREMENT — a population, an n, a number, and a verdict. Those are the
ones that must never be re-run from scratch, and they are exactly the ones that
were being re-discovered by hand.

Two outputs, deliberately separate:

  docs/reports/INDEX_ALL_REPORTS.md   — mechanical: every .md with its date and
                                        first heading. Generated, never edited.
  docs/reports/MEASUREMENTS.md        — curated: question / population / result /
                                        verdict / file. HAND-MAINTAINED above the
                                        marker; this script only appends newly
                                        seen candidate files below it, so a human
                                        judgement is never overwritten by a scan.

A measurement candidate is a report whose text carries an n= or a $ figure AND
one of the verdict words. That heuristic is deliberately loose: it is better to
list a file that turns out to be prose than to hide one that carried a number.

    python3 scripts/gen_measurement_index.py            # write both
    python3 scripts/gen_measurement_index.py --check    # fail if ALL is stale
"""
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORTS = ROOT / "docs" / "reports"
ALL_OUT = REPORTS / "INDEX_ALL_REPORTS.md"
MEAS_OUT = REPORTS / "MEASUREMENTS.md"
MARKER = "<!-- generated candidates below — hand-written rows stay above -->"

VERDICT_WORDS = ("verdict", "מסקנה", "recommend", "המלצה", "כדאי", "לא כדאי",
                 "GO", "NO-GO", "פסיקה", "הופרך", "אושש", "ratio", "יחס")
NUM_RE = re.compile(r"(?:\bn\s*=\s*\d+)|(?:[\$₪]\s?-?[\d,]+(?:\.\d+)?)")
DATE_RE = re.compile(r"(20\d\d-\d\d-\d\d)")


def _first_heading(text: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip()[:110]
        if line and not line.startswith("<!--"):
            return line[:110]
    return ""


def _git_date(path: Path) -> str:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ad", "--date=short", "--", str(path)],
            cwd=ROOT, capture_output=True, text=True, timeout=10)
        d = out.stdout.strip()
        if d:
            return d
    except Exception:
        pass
    m = DATE_RE.search(path.name)
    return m.group(1) if m else ""


def scan():
    rows = []
    for p in sorted(REPORTS.rglob("*.md")):
        if p.name in (ALL_OUT.name, MEAS_OUT.name):
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue
        head = _first_heading(text)
        has_num = bool(NUM_RE.search(text))
        has_verdict = any(w.lower() in text.lower() for w in VERDICT_WORDS)
        rows.append({
            "path": p.relative_to(ROOT).as_posix(),
            "name": p.name,
            "date": _git_date(p),
            "head": head,
            "measurement": has_num and has_verdict,
        })
    rows.sort(key=lambda r: (r["date"], r["name"]), reverse=True)
    return rows


def write_all(rows) -> str:
    out = [
        "# Index — every report file",
        "",
        "**Generated by `scripts/gen_measurement_index.py`. Do not edit by hand.**",
        "`M` marks a file that carries both a number and a verdict word — a",
        "measurement candidate. The curated ledger is `MEASUREMENTS.md`.",
        "",
        f"{len(rows)} files · {sum(1 for r in rows if r['measurement'])} carry a measurement",
        "",
        "| date | M | file | heading |",
        "|---|---|---|---|",
    ]
    for r in rows:
        head = r["head"].replace("|", "\\|")
        out.append(f"| {r['date']} | {'M' if r['measurement'] else ''} | "
                   f"[{r['name']}]({r['name']}) | {head} |")
    return "\n".join(out) + "\n"


def append_candidates(rows) -> int:
    """Append measurement candidates not already named anywhere in MEASUREMENTS.md."""
    if MEAS_OUT.exists():
        cur = MEAS_OUT.read_text(encoding="utf-8")
    else:
        cur = ("# Measurements ledger\n\n"
               "**What we already measured, and what it concluded.** Read this before\n"
               "commissioning any study — the answer may already be here.\n\n"
               "Rows above the marker are hand-written and authoritative: question,\n"
               "population, result, verdict. A measurement without an n and without a\n"
               "verdict is not a row — it is a note.\n\n"
               "| date | question | population / n | result | verdict | file |\n"
               "|---|---|---|---|---|---|\n\n" + MARKER + "\n")
    if MARKER not in cur:
        cur += "\n" + MARKER + "\n"
    head, tail = cur.split(MARKER, 1)
    added = 0
    lines = []
    for r in rows:
        if not r["measurement"]:
            continue
        if r["name"] in cur:
            continue
        lines.append(f"- `{r['date']}` [{r['name']}]({r['name']}) — {r['head']}")
        added += 1
    if lines:
        tail = tail.rstrip("\n") + "\n" + "\n".join(lines) + "\n"
    MEAS_OUT.write_text(head + MARKER + tail, encoding="utf-8")
    return added


def main():
    check = "--check" in sys.argv
    rows = scan()
    new_all = write_all(rows)
    if check:
        old = ALL_OUT.read_text(encoding="utf-8") if ALL_OUT.exists() else ""
        if old != new_all:
            print("🔴 INDEX_ALL_REPORTS.md is stale — run scripts/gen_measurement_index.py")
            sys.exit(1)
        print(f"✅ report index current — {len(rows)} files")
        return
    ALL_OUT.write_text(new_all, encoding="utf-8")
    added = append_candidates(rows)
    print(f"✅ wrote {ALL_OUT.relative_to(ROOT)} ({len(rows)} files, "
          f"{sum(1 for r in rows if r['measurement'])} measurements)")
    print(f"✅ {MEAS_OUT.relative_to(ROOT)}: {added} new candidate(s) appended")


if __name__ == "__main__":
    main()
