"""Pkg 0 · Redis migration · chart_5min → five_min

Generated by Pkg 0 per D-090.
Do NOT execute without Michael approval at G3.

Two options Michael decides at G3:
  A) RENAME — preserve in-flight state
       RENAME mems26:v9:chart_5min:latest mems26:v9:five_min:latest
       RENAME mems26:state:chart_5min mems26:state:five_min
  B) DROP — clean slate (recommended if no LIVE data yet)
       DEL mems26:v9:chart_5min:latest
       DEL mems26:state:chart_5min

Usage (after Michael picks A or B):
    python scripts/pkg0_redis_migrate.py --mode {rename|drop}

This script ONLY logs the operations it WOULD perform.
Actual Redis writes are guarded by --execute flag.
"""

import argparse
import logging
import sys

logger = logging.getLogger(__name__)

CHART_5MIN_KEYS = [
    "mems26:v9:chart_5min:latest",
    "mems26:state:chart_5min",
]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["rename", "drop"], required=True)
    parser.add_argument("--execute", action="store_true",
                        help="Actually perform Redis writes (default: dry-run log only)")
    args = parser.parse_args()

    client = None
    if args.execute:
        try:
            import redis
            redis_url = "redis://localhost:6379/0"
            client = redis.from_url(redis_url)
            client.ping()
            logger.info("[pkg0_redis_migrate] connected to Redis at %s", redis_url)
        except Exception as e:
            logger.warning("[pkg0_redis_migrate] redis unavailable: %s · dry-run only", e)
            args.execute = False

    for key in CHART_5MIN_KEYS:
        target = key.replace("chart_5min", "five_min")
        if args.mode == "rename":
            action = f"RENAME {key} → {target}"
            if args.execute and client:
                try:
                    client.rename(key, target)
                    logger.info("[pkg0_redis_migrate] executed: %s", action)
                except Exception as e:
                    logger.warning("[pkg0_redis_migrate] RENAME failed for %s: %s", key, e)
            else:
                logger.info("[pkg0_redis_migrate] DRY-RUN: would %s", action)
        else:
            action = f"DEL {key}"
            if args.execute and client:
                try:
                    client.delete(key)
                    logger.info("[pkg0_redis_migrate] executed: %s", action)
                except Exception as e:
                    logger.warning("[pkg0_redis_migrate] DEL failed for %s: %s", key, e)
            else:
                logger.info("[pkg0_redis_migrate] DRY-RUN: would %s", action)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    sys.exit(main() or 0)
