#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Does the Source-of-Truth map still describe the code it points at?

Michael 2026-09-01, after a work order named the wrong ATR variable:
*"למה הוא לא מתעדכן בכל פעם שאנחנו עובדים? איך זה נמנע לעולם ועד?"*

Two kinds of index live in this repo and only one of them can rot:

    SYSTEM_INDEX.md, docs/FLAG_INDEX.md   generated by a script from the code.
                                          Every run rebuilds them. Cannot rot.
    docs/SOURCE_OF_TRUTH.md               hand-written. It holds SEMANTIC
    docs/SYSTEM_MANIFEST.md               knowledge — "of these three ATRs,
                                          which one is canonical for the stop
                                          band" — which is not derivable from
                                          the code, so no generator can produce
                                          it. It rots.

And it does rot: CLAUDE.md records SOURCE_OF_TRUTH.md dying at 54 days and
SYSTEM_MANIFEST.md at 32. The map was revived and reached 47 days again, with no
ATR row at all — which is how a work order came to name
`five_min_system._current_atr_5m` as the stop band's ATR when the resolver never
reads it.

AGE IS THE WRONG TRIGGER. A correct map does not need editing because a month
passed, and a guard that cries every 30 days is one people learn to skip. What
matters is drift: **a file the map cites has changed since the map last did.**
That is a fact about this repo, checkable from git, and it fires only when there
is something real to re-read.

WHAT THIS CANNOT DO, stated plainly. It cannot detect a MISSING row — the actual
failure on 01.09 was a signal with no entry at all, and nothing mechanical knows
which signals deserve one. The mitigation for that half is procedural and lives
in the work-order rule: a spec that names a variable to change must paste the
file:line where the target mechanism READS it. No read-site, no spec. That rule
would have stopped the bad work order at the first sentence, because no such
line exists.

    python3 scripts/sot_map_guard.py            # report
    python3 scripts/sot_map_guard.py --strict   # exit 1 on drift (for guards)
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MAPS = ["docs/SOURCE_OF_TRUTH.md", "docs/SYSTEM_MANIFEST.md"]

# `backend/v9/foo.py` or backend/v9/foo.py:123 — inside backticks or bare.
CITE = re.compile(r'`?((?:backend|scripts|bridge|config|sc_study)/[\w./-]+\.(?:py|yaml|yml|cpp|json))(?::(\d+))?`?')


def _git_ts(path: str) -> int | None:
    """Last commit time of a path, or None if git does not know it."""
    try:
        out = subprocess.run(["git", "log", "-1", "--format=%ct", "--", path],
                             cwd=ROOT, capture_output=True, text=True, timeout=20)
        s = (out.stdout or "").strip()
        return int(s) if s else None
    except Exception:
        return None


def check(map_path: str) -> tuple[int, list[str]]:
    full = os.path.join(ROOT, map_path)
    if not os.path.exists(full):
        return 1, [f"🔴 {map_path} — missing entirely"]

    map_ts = _git_ts(map_path)
    if map_ts is None:
        return 1, [f"🔴 {map_path} — not committed; git cannot date it"]

    text = open(full, encoding="utf-8").read()
    cited = {}
    for m in CITE.finditer(text):
        cited.setdefault(m.group(1), set()).add(m.group(2))

    # A map that names almost no code reads GREEN here while being checked
    # against almost nothing — the confident-zero failure this repo keeps
    # rediscovering (empty shadow board, sot_health on a stale SQLite mirror).
    # Coverage is reported as a number, and an implausibly small one fails.
    MIN_CITED = 5
    if len(cited) < MIN_CITED:
        return 1, [
            f"🔴 {map_path} — cites only {len(cited)} source file(s). A map of "
            f"this system cannot honestly rest on that few.",
            f"   Green here would mean 'nothing I check has moved', not 'the map "
            f"is right' — so it fails instead of reassuring.",
            f"   Cite the file:line each row is about (that is also what makes a "
            f"row usable when someone is hunting for a value's real source).",
        ]

    drifted, gone = [], []
    for path, lines in sorted(cited.items()):
        fp = os.path.join(ROOT, path)
        if not os.path.exists(fp):
            gone.append(f"   {path} — cited but does not exist")
            continue
        # A cited line number past the end of the file is a stale pointer.
        for ln in sorted(x for x in lines if x):
            try:
                n = sum(1 for _ in open(fp, encoding="utf-8", errors="replace"))
                if int(ln) > n:
                    gone.append(f"   {path}:{ln} — file has only {n} lines")
            except Exception:
                pass
        ts = _git_ts(path)
        if ts and ts > map_ts:
            days = (ts - map_ts) / 86400.0
            drifted.append((days, f"   {path} — changed {days:.0f}d after the map"))

    out = []
    rc = 0
    if gone:
        rc = 1
        out.append(f"🔴 {map_path} — {len(gone)} broken reference(s):")
        out += gone[:10]
    if drifted:
        rc = 1
        drifted.sort(reverse=True)
        out.append(f"🔴 {map_path} — {len(drifted)} of {len(cited)} cited files "
                   f"changed after the map was last updated:")
        out += [d[1] for d in drifted[:10]]
        if len(drifted) > 10:
            out.append(f"   … and {len(drifted) - 10} more")
    if not out:
        out.append(f"✅ {map_path} — {len(cited)} cited files, none changed since")
    return rc, out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true",
                    help="exit 1 on drift (use from fire_drill / guard_tests)")
    a = ap.parse_args()

    rc = 0
    print()
    for m in MAPS:
        r, lines = check(m)
        rc |= r
        for ln in lines:
            print(ln)
        print()

    if rc:
        print("The map points at code that moved. Re-read those files and either")
        print("update the rows they belong to or confirm the rows still hold, then")
        print("commit the map — that timestamp is what clears this guard.")
        print()
        print("This is NOT a 'the file is old' complaint. It fires only because")
        print("cited code changed. A correct map that nothing touched stays green")
        print("forever, which is why it is worth obeying when it does fire.")
        print()
        print("🔴 And what it CANNOT see: a signal with no row at all. That was the")
        print("   01.09 failure. Its guard is the work-order rule — a spec naming a")
        print("   variable must paste the file:line where the target mechanism READS")
        print("   it. No read-site, no spec.")
    return rc if a.strict else 0


if __name__ == "__main__":
    raise SystemExit(main())
